[profile.default]
optimizer = false
optimizer_runs = 200
src = "src"
out = "out"
libs = ["lib", "erc6900_smart_contracts_lib/lib"]
via_ir = true
allow_paths = [
    "../node_modules",
    "../node_modules/@openzeppelin/contracts",
    "./erc6900_smart_contracts_lib"
]
remappings = [
    "forge-std/=lib/forge-std/src/",
    "@openzeppelin/contracts/=erc6900_smart_contracts_lib/lib/openzeppelin-contracts/contracts/",
    "@eth-infinitism/account-abstraction/=erc6900_smart_contracts_lib/lib/account-abstraction/contracts/"
]

solc = "0.8.22"

[rpc_endpoints]
sepolia = "${NEXT_PUBLIC_ALCHEMY_API_URL}"

[etherscan]
sepolia = { key = "${NEXT_PUBLIC_ETHERSCAN_API_KEY}" }

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
